### ISSUE TITLE
fdf/dsc .inc file syntax highlight

### ISSUE THREAD

**Issue by howdou** [WalonLi/edk2-vscode#11]
EDK2 has the included dsc/fdf file naming as xxx.dsc.inc and xxx.fdf.inc.
Such as:
NetworkPkg/Network.dsc.inc
NetworkPkg/Network.fdf.inc

Currently, the syntax highlight for dsc and fdf is great. Pease apply to the dsc.inc fdf.inc if possible. Thanks!

**Comment by WalonLi** [comment]
Thanks for your report. Since these files are not standard in edk2, I'm not prefer to apply.
Please see https://github.com/WalonLi/edk2-vscode/issues/8
