### ISSUE TITLE
Missing opcodes in VFR

### ISSUE THREAD

**Issue by nicklela** [WalonLi/edk2-vscode#12]
Hi @WalonLi 

It seems to me that below opcodes in VFR are missing color. Would you please add them if you have chance?

- namevaluevarstore
- orderedlist / endlist
- disableif
- ideqid
- pushthis
- resetbutton / endresetbutton
- formsetguid
- question
- guidop / endguidop
- formmap
- read
- modal
- refreshguid
- datatype

I got above opcodes from this file: https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Universal/DriverSampleDxe/Vfr.vfr

**Comment by WalonLi** [comment]
https://github.com/WalonLi/edk2-vscode/pull/15
@nicklela Thanks for catching this up! PR submitted.

**Comment by nicklela** [comment]
Pull request is reviewed. Thanks!

**Comment by WalonLi** [comment]
v1.0.9 is released now. close the issue.
