### ISSUE TITLE
Support dsc.inc and fdf.inc file type

### ISSUE THREAD

**Issue by nicklela** [WalonLi/edk2-vscode#13]
There is use case in edk2 that we will create dsc.inc and fdf.inc files for platform owner to include certain functions. The format is the same as regular DSC and FDF file. Could you please consider to support them together?

Reference:
- https://github.com/tianocore/edk2/blob/master/RedfishPkg/RedfishComponents.dsc.inc
- https://github.com/tianocore/edk2/blob/master/RedfishPkg/Redfish.fdf.inc

Thanks!
Nickle

**Comment by WalonLi** [comment]
Hi @nicklela,
I thought fdf.inc/dsc.inf are not defined in spec so I intend to not add syntax for this kind of files.
Please see my comment there. https://github.com/WalonLi/edk2-vscode/issues/8

**Comment by nicklela** [comment]
Ha! I see. Thanks for your response.
