### ISSUE TITLE
DSC outline is missing [Components]

### ISSUE THREAD

**Issue by clsheppard** [WalonLi/edk2-vscode#14]
Outstanding plugin!

The DSC code outline does not pick up `[Components]` sections.  In particular, `[Components.$(DXE_ARCH)]` and `[Components.$(PEI_ARCH)]` are excluded.  I mention those particulars just in case the references might be causing the trouble.

**Comment by WalonLi** [comment]
Hi @clsheppard,
Can you make an example for your problem? I checked INFs under Components and these are good.

**Comment by WalonLi** [comment]
@clsheppard please leave your comment otherwise will close this issue soon. Thanks.

**Comment by WalonLi** [comment]
Close the issue since no response.
