### ISSUE TITLE
edk2 is updated to use __func__ instead of __FUNCTION__

### ISSUE THREAD

**Issue by nhivp** [WalonLi/edk2-vscode#21]
https://github.com/WalonLi/edk2-vscode/blob/290db786b9b933063f8a0e4364b3ef15e4068672/src/extension.ts#L120

Can we make an update for debug marco? Or make it more flexible in user configuration?

**Comment by WalonLi** [comment]
@nhivp Not all old compilers support __func__ natively, and now I think many users are still maintaining old projects. Do you get any issue with any compilers?

**Comment by nhivp** [comment]
Tianocore/edk2 is using __func__ in their source. So, can we make an option for user selection of the style?

**Comment by WalonLi** [comment]
Create a new option is doable but it's too specific. Is there common term for that?

**Comment by WalonLi** [comment]
Close since no feedback.
