### ISSUE TITLE
[Feature request] List the section names on the right of the file name

### ISSUE THREAD

**Issue by JamesAmiTw** [WalonLi/edk2-vscode#3]
Hi Walon,

Is it possible to add a feature like other languages did?  
In the picture below, it lists all the functions and variables.  Can we list the sections of dsc/dec/inf like `[PcdFeatureFlag]`, `[Protocols]`, `[Sources]`, etc.  for better navigation.  Thanks!

![螢幕擷取畫面 2021-11-24 222542](https://user-images.githubusercontent.com/7878598/143256876-5407387a-b8ca-4a54-9228-7fb1d461255e.png)

**Comment by WalonLi** [comment]
Good idea, thanks @JamesAmiTw It's possible and not difficult to implement. I'll take time to do this this month(or two months?😊).

**Comment by JamesWangAmiTw** [comment]
@WalonLi

Thank you for the help! 💯   Just take your time.

**Comment by WalonLi** [comment]
@JamesWangAmiTw **1.0.5** is published. Outline function is ready for INF/DSC/DEC now. Please close if no more comment.
![1](https://user-images.githubusercontent.com/8321049/147323378-29819271-4384-4451-8774-57a22b80784f.JPG)
![2](https://user-images.githubusercontent.com/8321049/147323382-98c4817c-d8fe-48f9-ac88-eaf21094a2ef.JPG)

**Comment by JamesAmiTw** [comment]
@WalonLi Thank you for the effort!

I am closing this request.  

But... there is always a but XD

I was hoping that it can show the name on the top when focus is within the scope of the outline.  Take the  example below, it shows "..." only, not the "FeaturePcd" because the focus is on the `PcdPciBusHotplugDeviceSupport`
![圖片](https://user-images.githubusercontent.com/7878598/147400956-efa074f8-84de-4a7d-8167-831e29899a75.png)

It only show FeaturePcd when the focus is right on the [FeaturePcd] itself:
![圖片](https://user-images.githubusercontent.com/7878598/147400980-968fb3b1-c77e-44d9-9277-5cd2bf88ba8c.png)

Sometimes PCDs in the same section are more than a page and I have to open the side bar then search to check which section this PCD is belong to, or to just scroll pages up and up and up.  If it can directly show the section name where the focused line is belong to (on the top) it will help me to save some time.  This is my original intention but I didn't make it clearly described.

**Comment by WalonLi** [comment]
@JamesAmiTw Got it. Will submit a new PR and set you as reviewer for eliminating any gap between us. Thanks!

**Comment by JamesAmiTw** [comment]
@WalonLi Thank you!
