### ISSUE TITLE
The *.dsc.inc file type not support

### ISSUE THREAD

**Issue by Rayuu** [WalonLi/edk2-vscode#8]
Hello:
The *.dsc.inc file type not support.
May I add it by myself at settings?
or
Could you please add this type? 
Thanks!

![Snipaste_2022-03-24_16-48-51](https://user-images.githubusercontent.com/11494597/159878119-b365c63b-d14d-447f-a4d8-459f8283189b.png)
!

**Comment by WalonLi** [comment]
@Rayuu *.dsc.inc is not standard file in edk2 document. You can override setting by settings.json
![1](https://user-images.githubusercontent.com/8321049/160997722-034b582a-af06-4cf9-b046-891eb3d6ad7f.png)

**Comment by Rayuu** [comment]
OK,that's good,thanks!
