### ISSUE TITLE
The edk_dsc file would show words with the same color starting from symbol "<"

### ISSUE THREAD

**Issue by SteveWYLi** [WalonLi/edk2-vscode#9]
![test dsc](https://user-images.githubusercontent.com/97500573/163082588-58dfd93e-31ca-4344-b54b-22b39ea4dcec.png)

It seems the words are displayed with same color (brown?) starting from symbol "<" and this situation would disappear if I use ">".

**Comment by WalonLi** [comment]
@SteveWYLi Uploaded patch, please give me a feedback in #10

**Comment by SteveWYLi** [comment]
Thanks. It works normally in the patch.
